apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: u0bva4uhm-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:cb93b4ff57cc5e37af15d6ba21828b30a9607f6d@sha256:ba9ec3180d397cc2c374667297115d790035d84ca41d70312f1e3ec25fc59ef3
        name: container-image  
